version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_pass
      POSTGRES_DB: tu_bd
    ports:
      - "5432:5432"
