name: docs

on:
  push:
    branches: [ main ]
    paths: 
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.md'

permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install CLI tools
        run: |
          npm install -g markdownlint-cli conventional-changelog-cli markdown-toc

      - name: Lint Markdown
        run: markdownlint "**/*.md" --config .markdownlint.json \
               --ignore-pattern .markdownlintignore

      - name: Generate CHANGELOG & TOC
        run: |
          conventional-changelog -p angular -i CHANGELOG.md -s
          bash .github/scripts/update_docs.sh

      - name: Commit & push updates
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add CHANGELOG.md README.md docs/guia_desarrollo.md
          git commit -m "chore(docs): update changelog & TOC [skip ci]" || echo "No changes to commit"
          git push
