name: docs

on:
  push:
    branches: [ main ]

jobs:
  update-docs:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: Install dependencies
      run: |
        npm install markdown-toc-cli -g
        pip install conventional-changelog-cli

    - name: Generate CHANGELOG & TOC
      run: |
        conventional-changelog -p angular -i CHANGELOG.md -s
        update_docs.bat

    - name: Commit & push updates
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add CHANGELOG.md README.md docs/guia_desarrollo.md
        git commit -m "chore(docs): update changelog & TOC [skip ci]" || echo "No changes"
        git push