name: docs

# Esto otorga al GITHUB_TOKEN permiso para escribir en el repositorio
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  update-docs:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # Asegura que use el GITHUB_TOKEN para push
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install changelog & TOC tools
      run: |
        npm install -g conventional-changelog-cli markdown-toc

    - name: Generate CHANGELOG & TOC
      shell: cmd
      run: |
        conventional-changelog -p angular -i CHANGELOG.md -s
        call update_docs.bat

    - name: Commit & push updates
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add CHANGELOG.md README.md docs/guia_desarrollo.md
        git commit -m "chore(docs): update changelog & TOC [skip ci]" || echo "No changes to commit"
        git push